location: uksouth
name: python-aca
resourceGroup: aca-python
type: Microsoft.App/containerApps
properties:
  configuration:
    activeRevisionsMode: Single
    ingress:
      external: true
      allowInsecure: false
      targetPort: 80
      traffic:
        - latestRevision: true
          weight: 100
      transport: Auto
    registries:
    - identity: system
      passwordSecretRef: ''
      server: drhelius.azurecr.io
      username: ''
  template:
    containers:
      image: drhelius.azurecr.io/azqueue:latest
      name: azqueue
      resources:
        cpu: 2.0
        memory: 4Gi
      probes:
      - type: readiness
        httpGet:
          path: "/health"
          port: 8080
        initialDelaySeconds: 0
        periodSeconds: 1
    scale:
      maxReplicas: 50
      minReplicas: 5